server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: 20001029
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
mybatis:
  type-aliases-package: com.leyou.pojo
eureka:
    client:
      service-url:
        defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka