server:
  port: 8083
spring:
  application:
    name: consumer
eureka:
    client:
      service-url:
        defaultZone: http://127.0.0.1:10087/eureka
      registry-fetch-interval-seconds: 5
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
